apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temperature-api
  template: # containers usados
    metadata:
      labels:
        app: temperature-api
    spec:
      containers:
      - name: temperature-api
        # imagem do projeto deste diretório
        image: gustaff77/temperature_conversion:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: temperature-api
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30000
  type: NodePort
